[workspace]
resolver = "3"
members = ["apps/backend", "apps/pubtator3", "apps/pubtator3-hpo", "apps/openai", "apps/biomedical_graph"]

[workspace.dependencies]
openai = { path = "apps/openai" }
sqlx = { version = "0.9.0", default-features = false, features = ["runtime-tokio", "sqlite", "uuid", "chrono", "derive", "migrate", "macros"] }
