-- SQLite has no native enums: Rust enums map to TEXT with CHECK constraints.
-- UUIDs are generated by the application, stored as 16-byte blobs, and returned as strings.
CREATE TABLE users (
    id BLOB PRIMARY KEY NOT NULL CHECK (length(id) = 16),
    email TEXT NOT NULL UNIQUE CHECK (email = lower(email) AND length(email) BETWEEN 3 AND 254),
    username TEXT NOT NULL UNIQUE CHECK (length(username) BETWEEN 3 AND 32 AND username NOT GLOB '*[^a-z0-9_]*'),
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'scientist', 'pharma_scout')),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
) STRICT;

CREATE TABLE sessions (
    token_hash BLOB PRIMARY KEY NOT NULL CHECK (length(token_hash) = 32),
    user_id BLOB NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    expires_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '+30 days'))
) STRICT;
CREATE INDEX sessions_user_id_idx ON sessions(user_id);
CREATE INDEX sessions_expires_at_idx ON sessions(expires_at);

CREATE TABLE communities (
    id BLOB PRIMARY KEY NOT NULL CHECK (length(id) = 16),
    slug TEXT NOT NULL UNIQUE CHECK (slug NOT GLOB '*[^a-z0-9-]*' AND slug NOT LIKE '-%' AND slug NOT LIKE '%-' AND instr(slug, '--') = 0 AND length(slug) BETWEEN 3 AND 80),
    name TEXT NOT NULL CHECK (length(trim(name)) BETWEEN 1 AND 100),
    description TEXT NOT NULL DEFAULT '' CHECK (length(description) <= 5000),
    created_by BLOB NOT NULL REFERENCES users(id),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
) STRICT;

CREATE TABLE community_members (
    community_id BLOB NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
    user_id BLOB NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    joined_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    PRIMARY KEY (community_id, user_id)
) STRICT;
CREATE INDEX community_members_user_id_idx ON community_members(user_id);

CREATE TABLE channels (
    id BLOB PRIMARY KEY NOT NULL CHECK (length(id) = 16),
    community_id BLOB NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
    slug TEXT NOT NULL CHECK (slug NOT GLOB '*[^a-z0-9-]*' AND slug NOT LIKE '-%' AND slug NOT LIKE '%-' AND instr(slug, '--') = 0 AND length(slug) BETWEEN 3 AND 80),
    name TEXT NOT NULL CHECK (length(trim(name)) BETWEEN 1 AND 100),
    kind TEXT NOT NULL DEFAULT 'discussion' CHECK (kind IN ('discussion', 'announcement')),
    position INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    UNIQUE (community_id, slug),
    UNIQUE (id, community_id)
) STRICT;
CREATE UNIQUE INDEX channels_one_announcement_per_community_idx
    ON channels(community_id) WHERE kind = 'announcement';

-- Announcements are threads in an announcement channel, so they support comments too.
CREATE TABLE threads (
    id BLOB PRIMARY KEY NOT NULL CHECK (length(id) = 16),
    community_id BLOB NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
    channel_id BLOB NOT NULL,
    author_id BLOB NOT NULL REFERENCES users(id),
    title TEXT NOT NULL CHECK (length(trim(title)) BETWEEN 1 AND 300),
    body TEXT NOT NULL CHECK (length(trim(body)) BETWEEN 1 AND 40000),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    UNIQUE (id, community_id),
    FOREIGN KEY (channel_id, community_id) REFERENCES channels(id, community_id) ON DELETE CASCADE
) STRICT;
CREATE INDEX threads_channel_created_idx ON threads(channel_id, created_at DESC, id DESC);
CREATE INDEX threads_community_created_idx ON threads(community_id, created_at DESC, id DESC);
CREATE INDEX threads_author_id_idx ON threads(author_id);

CREATE TABLE comments (
    id BLOB PRIMARY KEY NOT NULL CHECK (length(id) = 16),
    community_id BLOB NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
    thread_id BLOB NOT NULL,
    author_id BLOB NOT NULL REFERENCES users(id),
    parent_id BLOB,
    body TEXT NOT NULL CHECK (length(trim(body)) BETWEEN 1 AND 10000),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    UNIQUE (id, thread_id, community_id),
    FOREIGN KEY (thread_id, community_id) REFERENCES threads(id, community_id) ON DELETE CASCADE,
    FOREIGN KEY (parent_id, thread_id, community_id) REFERENCES comments(id, thread_id, community_id),
    CHECK (parent_id IS NULL OR parent_id <> id)
) STRICT;
CREATE INDEX comments_thread_created_idx ON comments(thread_id, created_at, id);
CREATE INDEX comments_community_created_idx ON comments(community_id, created_at, id);
CREATE INDEX comments_parent_idx ON comments(parent_id, thread_id, community_id);
CREATE INDEX comments_author_id_idx ON comments(author_id);

-- A canonical pair guarantees one private conversation per pair of users.
CREATE TABLE dm_conversations (
    id BLOB PRIMARY KEY NOT NULL CHECK (length(id) = 16),
    user_low_id BLOB NOT NULL REFERENCES users(id),
    user_high_id BLOB NOT NULL REFERENCES users(id),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    CHECK (user_low_id < user_high_id),
    UNIQUE (user_low_id, user_high_id)
) STRICT;
CREATE INDEX dm_conversations_high_user_idx ON dm_conversations(user_high_id);

CREATE TABLE dm_messages (
    id BLOB PRIMARY KEY NOT NULL CHECK (length(id) = 16),
    conversation_id BLOB NOT NULL REFERENCES dm_conversations(id) ON DELETE CASCADE,
    author_id BLOB NOT NULL REFERENCES users(id),
    body TEXT NOT NULL CHECK (length(trim(body)) BETWEEN 1 AND 10000),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
) STRICT;
CREATE INDEX dm_messages_conversation_created_idx ON dm_messages(conversation_id, created_at DESC, id DESC);
CREATE INDEX dm_messages_author_id_idx ON dm_messages(author_id);
